### ISSUE TITLE
Update Webmaker logo 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/blog.webmaker.org#15]
@vazquez - can you share an appropriate file? @mmmavis - can you swap old with the new? If not you, then who? Thanks!

**Comment by vazquez** [comment]
Logo is available here: https://drive.google.com/open?id=0B2qu3ExKWIlvckVJNDI2TWdERTQ

**Comment by mmmavis** [comment]
Thanks, I'll get this updated today :smile:

**Comment by mmmavis** [comment]
done done https://blog.webmaker.org/ :tada:

**Comment by xmatthewx** [comment]
dang. that looks nice. cc @lovegushwa
